# Documentation: https://ztextgenerator.groupez.dev/

# Enables detailed logging and debugging messages in the console.
enable-debug: false

# Default language used for texts and books.
default-language: en_us

# Default inventory size and name used for text displays.
text-inventory-size: 54
text-inventory-name: ""

# Validation system used with the command /text alphabet validation <alphabet>.
# This tool helps you verify that each character in your custom alphabet
# is properly displayed and aligned within the inventory interface.
validation:
  # Number of letters displayed per line.
  letters-per-line: 10
  # Maximum number of lines displayed.
  max-lines: 6
  # Inventory name used during alphabet validation.
  inventory-name: ":offset_-48::generic_dark_full::offset_-168:"
  # Inventory size used during alphabet validation.
  inventory-size: 54
