enable-debug: true
default-language: en_us

text-inventory-size: 54
text-inventory-name: ""

# Allows horizontal text adjustment.
# For ItemsAdder you should use: :offset_%pixels%: - https://itemsadder.devs.beer/plugin-usage/adding-content/font-images#offsets
# For Oraxen you should use: <shift:%pixels%> - https://docs.oraxen.com/configuration/glyphs/custom-gui#how-do-i-get-the-unicode-for-the-glyph
# For Nexos you should use: <shift:%pixels%> - https://docs.nexomc.com/configuration/glyphs#custom-guis
offset: ":offset_%pixels%:"

validation:
  letters-per-line: 10
  max-lines: 6
  inventory-name: ":offset_-48::generic_dark_full::offset_-168:"
  inventory-size: 54

