name: zTextGenerator
version: '1.0.0'
main: fr.maxlego08.text.TextPlugin
api-version: '1.21'
authors: [ Maxlego08 ]
description: Add texts inside your inventories
website: https://groupez.dev/
depend:
  - PlaceholderAPI
soft-depend:
  - ItemsAdder
  - Nexo
  - Oraxen
  - zMenu